### ISSUE TITLE
Stats reset daily

### ISSUE THREAD

**Issue by theleemon** [artifex404/wp-power-stats#3]
I use WP Power Stats on a number of different sites, but on one of them, stats are reset daily. Maybe it's a combination of specific PHP and MySQL versions.

I managed to fix this issue on the problematic site changing one line in the power_stats_purge() function in the wp-power-stats.php file:

Replace this:

``self::$wpdb->query("DELETE FROM {$GLOBALS['wpdb']->prefix}power_stats_visits WHERE `date` < $days_ago");``

with this:

``self::$wpdb->query("DELETE FROM {$GLOBALS['wpdb']->prefix}power_stats_visits WHERE `date` < FROM_UNIXTIME($days_ago)");``

**Comment by artifex404** [comment]
Thanks! Will release the bugfix!
